server:
  port: 80
  address: 127.0.0.1

spring:
  application:
    name: blog
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: blog
    password: blog
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl